### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by dentex** [hasancse91/Android-CardView-RecyclerView#2]
Thanks for this nice library.
Do you mind to add a license file to it? I would like to include this lib in a product (... if I'll ever finish it).

Thanks.

**Comment by hasancse91** [comment]
> Thanks for this nice library.
> Do you mind to add a license file to it? I would like to include this lib in a product (... if I'll ever finish it).
> 
> Thanks.

MIT License added.
Thanks.
